import type { FeedbakkrSchema, SchemaField } from "./schema-types.js";

const HEADER = "// Generated by @feedbakkr/cli — do not edit manually\n";

/**
 * Convert a Feedbakkr schema to a TypeScript interface.
 *
 * @param schema - The Feedbakkr schema DSL object.
 * @param typeName - The name for the generated TypeScript interface.
 * @returns TypeScript source code as a string.
 */
export function schemaToTypeScript(schema: FeedbakkrSchema, typeName: string): string {
	if (!schema.fields || schema.fields.length === 0) {
		return `${HEADER}\nexport interface ${typeName} {\n  // No fields defined\n}\n`;
	}

	const lines: string[] = [HEADER];

	if (schema.title) {
		lines.push(`/** ${schema.title} */`);
	}
	lines.push(`export interface ${typeName} {`);

	for (const field of schema.fields) {
		const tsType = fieldToTsType(field);
		const optional = field.req ? "" : "?";
		const comment = field.label ? ` /** ${field.label} */` : "";
		lines.push(`${comment}`);
		lines.push(`  ${sanitizeKey(field.k)}${optional}: ${tsType};`);
	}

	lines.push("}");
	lines.push("");

	return lines.join("\n");
}

function fieldToTsType(field: SchemaField): string {
	switch (field.t) {
		case "text":
		case "textarea":
		case "date":
			return "string";
		case "bool":
			return "boolean";
		case "number":
			return "number";
		case "fixed":
			if (field.opts && field.opts.length > 0) {
				return field.opts.map((o) => JSON.stringify(o.k)).join(" | ");
			}
			return "string";
		case "dynlist":
			if (field.item) {
				const itemType = fieldToTsType(field.item);
				const needsParens = itemType.includes(" | ");
				return needsParens ? `(${itemType})[]` : `${itemType}[]`;
			}
			return "unknown[]";
		default:
			return "unknown";
	}
}

function sanitizeKey(key: string): string {
	if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
		return key;
	}
	return JSON.stringify(key);
}

/**
 * Derive a PascalCase type name from a file path or schema title.
 */
export function deriveTypeName(input: string): string {
	const base = input
		.replace(/\.(schema\.json|json|ts)$/i, "")
		.replace(/.*[\\/]/, "");

	const pascal = base
		.replace(/[-_.]+/g, " ")
		.replace(/\b\w/g, (c) => c.toUpperCase())
		.replace(/\s+/g, "");

	if (!pascal || !/^[A-Z]/.test(pascal)) {
		return "FeedbakkrFields";
	}

	return pascal.endsWith("Fields") ? pascal : `${pascal}Fields`;
}
