import { describe, it, expect } from "vitest";
import { schemaToTypeScript, deriveTypeName } from "../src/lib/schema-to-typescript.js";
import type { FeedbakkrSchema } from "../src/lib/schema-types.js";

function schema(fields: FeedbakkrSchema["fields"], title?: string): FeedbakkrSchema {
	return { v: 1, fields, ...(title ? { title } : {}) };
}

describe("schemaToTypeScript", () => {
	it("generates interface for text fields", () => {
		const result = schemaToTypeScript(
			schema([
				{ k: "name", t: "text", label: "Name", req: true },
				{ k: "bio", t: "textarea", label: "Bio" },
			]),
			"ContactFields",
		);

		expect(result).toContain("export interface ContactFields {");
		expect(result).toContain("name: string;");
		expect(result).toContain("bio?: string;");
		expect(result).toContain("/** Name */");
		expect(result).toContain("/** Bio */");
	});

	it("generates boolean type", () => {
		const result = schemaToTypeScript(
			schema([{ k: "agree", t: "bool", label: "Agree", req: true }]),
			"FormFields",
		);
		expect(result).toContain("agree: boolean;");
	});

	it("generates number type", () => {
		const result = schemaToTypeScript(
			schema([{ k: "rating", t: "number", label: "Rating" }]),
			"FormFields",
		);
		expect(result).toContain("rating?: number;");
	});

	it("generates date as string", () => {
		const result = schemaToTypeScript(
			schema([{ k: "dob", t: "date", label: "Date of Birth", req: true }]),
			"FormFields",
		);
		expect(result).toContain("dob: string;");
	});

	it("generates union type for fixed fields", () => {
		const result = schemaToTypeScript(
			schema([
				{
					k: "priority",
					t: "fixed",
					label: "Priority",
					req: true,
					opts: [
						{ k: "low", label: "Low" },
						{ k: "medium", label: "Medium" },
						{ k: "high", label: "High" },
					],
				},
			]),
			"TicketFields",
		);
		expect(result).toContain('priority: "low" | "medium" | "high";');
	});

	it("generates array type for dynlist fields", () => {
		const result = schemaToTypeScript(
			schema([
				{
					k: "tags",
					t: "dynlist",
					label: "Tags",
					item: { k: "tag", t: "text", label: "Tag" },
				},
			]),
			"FormFields",
		);
		expect(result).toContain("tags?: string[];");
	});

	it("generates dynlist with fixed item type", () => {
		const result = schemaToTypeScript(
			schema([
				{
					k: "choices",
					t: "dynlist",
					label: "Choices",
					req: true,
					item: {
						k: "choice",
						t: "fixed",
						label: "Choice",
						opts: [{ k: "a" }, { k: "b" }],
					},
				},
			]),
			"FormFields",
		);
		expect(result).toContain('choices: ("a" | "b")[];');
	});

	it("marks required fields without ? and optional with ?", () => {
		const result = schemaToTypeScript(
			schema([
				{ k: "required_field", t: "text", label: "Required", req: true },
				{ k: "optional_field", t: "text", label: "Optional" },
				{ k: "explicit_optional", t: "text", label: "Explicit", req: false },
			]),
			"TestFields",
		);
		expect(result).toContain("required_field: string;");
		expect(result).toContain("optional_field?: string;");
		expect(result).toContain("explicit_optional?: string;");
	});

	it("includes header comment", () => {
		const result = schemaToTypeScript(schema([]), "EmptyFields");
		expect(result).toContain("// Generated by @feedbakkr/cli");
	});

	it("includes title as JSDoc if present", () => {
		const result = schemaToTypeScript(
			schema([{ k: "x", t: "text", label: "X" }], "Contact Us Form"),
			"ContactFields",
		);
		expect(result).toContain("/** Contact Us Form */");
	});

	it("handles empty fields array", () => {
		const result = schemaToTypeScript(schema([]), "EmptyFields");
		expect(result).toContain("export interface EmptyFields {");
		expect(result).toContain("// No fields defined");
	});

	it("handles fixed field with no opts (fallback to string)", () => {
		const result = schemaToTypeScript(
			schema([{ k: "status", t: "fixed", label: "Status", opts: [] }]),
			"F",
		);
		expect(result).toContain("status?: string;");
	});
});

describe("deriveTypeName", () => {
	it("derives PascalCase from file name", () => {
		expect(deriveTypeName("contact-form.schema.json")).toBe("ContactFormFields");
	});

	it("handles nested paths", () => {
		expect(deriveTypeName("./feedbakkr/contact.schema.json")).toBe("ContactFields");
	});

	it("handles underscores and dots", () => {
		expect(deriveTypeName("my_form.json")).toBe("MyFormFields");
	});

	it("does not double-append Fields", () => {
		expect(deriveTypeName("contact-fields.json")).toBe("ContactFields");
	});

	it("returns fallback for empty string", () => {
		expect(deriveTypeName("")).toBe("FeedbakkrFields");
	});
});
